### PR TITLE
parser edit for markdown results.

### PR DESCRIPTION
**Pull request by Jeongyong-park**
- apply standard code style.
- apply generator for markdown results.
- 
#48

### CODE REVIEW

**Comment by Jeongyong-park** [comment]
it will be make result show like this below 

image

**Comment by Jeongyong-park** [comment]
As Is:
[https://github.com/OpenDroneMap/odm-benchmarks/blob/master/data-parsed/by-dataset.txt](https://github.com/OpenDroneMap/odm-benchmarks/blob/master/data-parsed/by-dataset.txt)

[https://github.com/OpenDroneMap/odm-benchmarks/blob/master/data-parsed/by-version.txt](https://github.com/OpenDroneMap/odm-benchmarks/blob/master/data-parsed/by-version.txt)

To Be:
[https://github.com/Jeongyong-park/odm-benchmarks/blob/parser/data-parsed/by-dataset.md](https://github.com/Jeongyong-park/odm-benchmarks/blob/parser/data-parsed/by-dataset.md)


[https://github.com/Jeongyong-park/odm-benchmarks/blob/parser/data-parsed/by-version.md](https://github.com/Jeongyong-park/odm-benchmarks/blob/parser/data-parsed/by-version.md)

**Comment by coreysnipes** [comment]
Sorry, just need a few more days to get through some $dayjob work and I'll have a look.  Sounds like a good and useful improvement!

**Comment by coreysnipes** [comment]
This is great.  Thank you for putting it together!

**Comment by coreysnipes** [comment]
Actually, testing further, this parser isn't working for me.  It stops after displaying the following three lines and does not create the output .md files:
`
Num defined datasets: 21
Num benchmark records: 233
Parsing unique datasets
`
I did run npm update to pick up the package changes.  I am running 'node app.js' in the parser dir, as before.

My local node version is 16.20.2

Any ideas?

**Comment by Jeongyong-park** [comment]
> Actually, testing further, this parser isn't working for me. It stops after displaying the following three lines and does not create the output .md files: `Num defined datasets: 21 Num benchmark records: 233 Parsing unique datasets` I did run npm update to pick up the package changes. I am running 'node app.js' in the parser dir, as before.
> 
> My local node version is 16.20.2
> 
> Any ideas?

I really Sorry about that problems. I fixed in #51

**Comment by coreysnipes** [comment]
@Jeongyong-park Thank you again for updating this to use Markdown outputs.  The Markdown files are so much nicer to use when updating and working with the benchmark data.

**Pull request merged**
